=== AbdullahWB/JavaWebDev/XML, DTD and XML Schema Exercises/employe/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="StudentRoster">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Student" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string" />
                <xs:element name="Gender" type="GenderType" />
                <xs:element name="Age" type="AgeType" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="GenderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Male" />
            <xs:enumeration value="Female" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AgeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="150" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== AbdullahWB/JavaWebDev/XML, DTD and XML Schema Exercises/employe/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<StudentRoster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="students.xsd">

    <Student id="1">
        <Name>Zhang San</Name>
        <Gender>Male</Gender>
        <Age>200</Age>
    </Student>

    <Student id="2">
        <Name>Li Si</Name>
        <Gender>Female</Gender>
        <Age>19</Age>
    </Student>

    <Student id="3">
        <Name>Wang Wu</Name>
        <Gender>Male</Gender>
        <Age>21</Age>
    </Student>

</StudentRoster>
